FROM nginx:alpine
COPY conf/apiGateway.conf /etc/nginx/conf.d/default.conf
COPY errors /etc/nginx/errors
COPY public /usr/share/nginx/html
VOLUME var/log/nginx/log
VOLUME etc/nginx
ENV PORT 80
EXPOSE 80
RUN ["/bin/bash", "-c", "ls"]
 