FROM node
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
# Bundle app source
COPY ./conf/apiGateway.conf /etc/nginx/conf.d/default.conf
COPY ./errors/ /etc/nginx/errors
VOLUME /var/log/nginx/log
VOLUME /etc/nginx
ENV PORT 80
EXPOSE 80
 